GET localhost:8080/v1/todo

###

POST localhost:8080/v1/todo

###

POST localhost:8080/v1/todo/10

###

POST localhost:8080/v1/auth

{
  "username": {
    "value": "string"
  },
  "password": {
    "value": "string"
  }
}
###

POST localhost:8080/v1/auth/new

{
  "username": {
    "value": "string"
  },
  "password": {
    "value": "string"
  }
}
###